/*
COUNTRY_TEST 테이블 생성
COUNTRY_ID 컬럼   - NULL허용X, PK
COUNTRY_NAME 컬럼 - NULL허용X
*/
CREATE TABLE COUNTRY_TEST(
    COUNTRY_ID NUMBER PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(100) NOT NULL
    )

/*
REGION_ID 컬럼 추가 (NULL 허용)
*/
ALTER TABLE COUNTRY_TEST
ADD REGION_ID NUMBER

/*
REGION_ID 컬럼 변경
*/
ALTER TABLE COUNTRY_TEST
MODIFY REGION_ID NOT NULL;

/*
COUNTRY_TEST 테이블 삭제
*/
DROP TABLE COUNTRY_TEST;

-- COUNTRY_TEST 테이블 불러오기
DESC COUNTRY_TEST;

-- LOCATIONS 테이블 불러오기
DESC LOCATIONS

/*
LOCATION_ID가 2000이상 3000이하인 데이터 추출
*/
SELECT *
FROM LOCATIONS
WHERE LOCATION_ID >= 2000 AND LOCATION_ID <= 3000

/*
MANAGER_ID 컬럼이 NULL인 데이터 추출 (상관이 없는 사람- 사장)
*/           
SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL

/*
COMMISSION_PCT가 NULL이면 SALARY만
COMMISSION_PCT에 값이 있으면 SALARY * COMMISSION_PCT 값을 추출
*/           
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT,
            CASE WHEN COMMISSION_PCT IS NULL THEN SALARY
            ELSE SALARY + (SALARY * COMMISSION_PCT) END AS TOTAL
FROM EMPLOYEES

/*
ROWNUM - 행 번호
WHERE절에서 행 번호를 조건으로 걸 수 있는데
ROWNUM < n 이면 n보다 작은 최대 정수의 값만큼 출력된다.
*/
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE ROWNUM < 2

/*
LIKE 'S%' 로 'S'가 포함된 데이터 구하기
*/
SELECT *
FROM LOCATIONS
WHERE CITY LIKE 'S%'
ORDER BY CITY DESC

/*
|| 연산자로 문자 붙이기
*/
SELECT (POSTAL_CODE || ' - ' || STREET_ADDRESS || ' - ' || CITY || ' - ' || STATE_PROVINCE || ' - ' || COUNTRY_ID) 주소
FROM LOCATIONS
WHERE COUNTRY_ID = 'US'

/*
POSTAL_CODE가 NULL인 데이터 제외
*/
SELECT (POSTAL_CODE || ' - ' || STREET_ADDRESS || ' - ' || CITY || ' - ' || STATE_PROVINCE || ' - ' || COUNTRY_ID) 주소
FROM LOCATIONS
WHERE COUNTRY_ID = 'UK' AND POSTAL_CODE IS NOT NULL

/*
POSTAL_CODE가 NULL 이면 99999로 대체
*/
SELECT CASE WHEN POSTAL_CODE IS NULL
    THEN ('99999 - ' || STREET_ADDRESS || ' - ' || CITY || ' - ' || STATE_PROVINCE || ' - ' || COUNTRY_ID)
    ELSE (POSTAL_CODE || ' - ' || STREET_ADDRESS || ' - ' || CITY || ' - ' || STATE_PROVINCE || ' - ' || COUNTRY_ID) END 주소
FROM LOCATIONS
WHERE COUNTRY_ID = 'UK'
