-- 급여가 10000 이상인 사원의 평균 급여
SELECT ROUND(AVG(SALARY),0)
FROM EMPLOYEES
WHERE SALARY > 10000

-- 입사 월별 사원 수
SELECT TO_CHAR(HIRE_DATE, 'MM'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'MM')
ORDER BY 1

-- 요일별 입사 사원 수
SELECT TO_CHAR(HIRE_DATE, 'DAY'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'DAY')
ORDER BY 1

-- 요일을 순서대로 하고 싶으면
SELECT TO_CHAR(HIRE_DATE, 'D'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'D')
ORDER BY 1

-- 이름이 동일한 사원과 동일인 수를 구하라
SELECT FIRST_NAME, COUNT(*)
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*) >= 2
ORDER BY FIRST_NAME
