/*
각 국가별 사무소 개수
*/
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID
ORDER BY 1

/*
분기별 입사자 수 (분기는 TO_CHAR(날짜,'Q')로 추출 가능)
*/
SELECT TO_CHAR(HIRE_DATE, 'Q'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'Q')
ORDER BY 1

/*
직군별 평균 금여를 AVG()로 구한 컬럼과 (AVG_SALARY),
직접 계산(전체 합계/직원수)하여 구한 컬럼 (AVG_SALARY1) 비교
*/
SELECT JOB_ID, ROUND(AVG(SALARY), 0) AVG_SALARY
    , ROUND(SUM(SALARY) / COUNT(*), 0) AVG_SALARY1
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY 1

/*
코로나 확진 데이터에서 우리나라 월별 코로나 확진자 총합 구하기
*/
SELECT ISO_CODE AS 국가, TO_CHAR(DATES, 'YYYY-MM') 연월, SUM(NEW_CASES) 확진자수
FROM COVID19_TEST
WHERE ISO_CODE = 'KOR'
GROUP BY ISO_CODE, TO_CHAR(DATES, 'YYYY-MM')
ORDER BY 2

/*
우리나라 월별 코로나 확진자 수와 사망자 수를 구하고 사망률 구하기
분모가 되는 확진자 수가 0일때는 예외처리를 추가
*/
SELECT TO_CHAR(DATES, 'YYYY-MM') 연월, SUM(NEW_CASES) 확진자수, SUM(NEW_DEATHS) 사망자수
    , CASE WHEN SUM(NEW_CASES) = 0 THEN 0 ELSE ROUND(SUM(NEW_DEATHS) / SUM(NEW_CASES) * 100, 2) END 사망률
FROM COVID19_TEST
WHERE ISO_CODE = 'KOR'
GROUP BY ISO_CODE, TO_CHAR(DATES, 'YYYY-MM')
ORDER BY 2

/*
2020년 10월에 가장 많은 확진자가 나온 국가 순으로 정렬
전 세계기록 (OWID_WRL)은 제외하고, 확진자 수가 NULL인 값을 제외하여 불필요한 정보가 상단에 뜨지 않도록 제어
*/
SELECT COUNTRY 국가, SUM(NEW_CASES) 확진자수
FROM COVID19_TEST
WHERE TO_CHAR(DATES, 'YYYY-MM') = '2020-10' AND COUNTRY <> 'World' AND NEW_CASES IS NOT NULL
GROUP BY COUNTRY, TO_CHAR(DATES, 'YYYY-MM')
ORDER BY 2 DESC



/*
집합연산자를 이용하여 2001년 입사자와 2003년 입사자의 데이터 조회하기
*/
SELECT EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2001
UNION
SELECT EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2003

/*
JOB_ID별로 급여 총합을 구하고, 전체 급여 총합을 UNION으로 붙이기
*/
SELECT JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
UNION
SELECT 'TOTAL', SUM(SALARY)
FROM EMPLOYEES

/*
전반기 확진자 10,000명 이상을 기록하고, 하반기 확진자 1,000명 이하를 기록한 나라를
INTERSECT를 이용하여 구하기
*/
SELECT DISTINCT COUNTRY 국가
FROM COVID19_TEST
WHERE TO_CHAR(DATES,'MM') >= '01' AND TO_CHAR(DATES,'MM') <= '06'
GROUP BY ISO_CODE, COUNTRY, TO_CHAR(DATES,'MM')
HAVING SUM(NEW_CASES) >= 10000
INTERSECT
SELECT DISTINCT COUNTRY 국가
FROM COVID19_TEST
WHERE TO_CHAR(DATES,'MM') >= '07' AND TO_CHAR(DATES,'MM') <= '10'
GROUP BY ISO_CODE, COUNTRY, TO_CHAR(DATES,'MM')
HAVING SUM(NEW_CASES) <= 1000

